updated preinst and postinst to behave properly during upgrdes

diff --git a/DEBIAN/prerm b/DEBIAN/prerm
--- a/DEBIAN/prerm
+++ b/DEBIAN/prerm
@@ -1,36 +1,42 @@
 #!/bin/bash
 #------------------------------------------------------------------------------
 #
-# example post installation script
+# Package: thinkpad-dock
 #
+# Provides: prerm - pre-removal script
 #
 #------------------------------------------------------------------------------
 #--- Main Code
 #------------------------------------------------------------------------------
-#
-# This file does nothing, please edit to suit your needs
-#
 
-scripts="$( ls /etc/thinkpad-dock/scripts/ )"
+remove_package()
+{
+   scripts="$( ls /etc/thinkpad-dock/scripts/ )"
 
-if [[ -z ${scripts} ]]
-then
-   rm -rf /etc/thinkpad-dock/scripts/
-else
-   echo "ERR: /etc/thinkpad-dock/scripts/ is not empty, not removing"
-fi
+   if [[ -z ${scripts} ]]
+   then
+      rm -rf /etc/thinkpad-dock/scripts/
+   else
+      echo "INFO: /etc/thinkpad-dock/scripts/ is not empty, not removing"
+   fi
 
-if systemctl disable thinkpad-dock.service
-then
-   rm -f /etc/systemd/system/thinkpad-dock.service
-else
-   echo "ERR: unable to remove thinkpad-dock.service"
-   exit 1
-fi
+   if systemctl disable thinkpad-dock.service
+   then
+      rm -f /etc/systemd/system/thinkpad-dock.service
+   else
+      echo "ERR: unable to remove thinkpad-dock.service"
+      return 1
+   fi
+}
 
-exit 0
+case $1 in
+   remove|purge)
+      remove_package || exit $?
+      ;;
+   *) exit 0
+      ;;
+esac
 
-#
 #------------------------------------------------------------------------------
 #--- End Script
 #------------------------------------------------------------------------------
